// ═══════════════════════════════════════════════════════════════════
// TODO.identity-ops/02 — the key-rotation ceremony, proven against a
// LOCAL stack: the identity-profile API boots twice against ONE SQLite
// file, first with OP_SIGNING_KEY = key A, then with the successor key
// B (the script's own generation), and the ceremony's assertions run
// against the live JWKS:
//
//   1. the script's kid derivation is the OP's own (keys.ts's kidFor):
//      the kid the script announces for a generated pair IS the kid the
//      OP advertises once it signs with it;
//   2. the overlap: after the rotation the JWKS advertises BOTH keys
//      (pollJwksKids), and an ID token signed with the OLD key still
//      verifies through the RP's REAL validator (auth/oidc.ts's
//      validateIdToken) against that JWKS — an in-flight token is never
//      stranded;
//   3. the retirement: after the documented admin act (the oidc_keys
//      UPDATE) the old kid leaves the JWKS answer, the new kid stays,
//      and the old token now fails honestly.
//
// The --apply path (the wrangler secret put) has no local secret store;
// it is exercised by the operator against the real deployment, and its
// building blocks (the generation, the overlap assert, the retirement
// note) are what this suite pins.
//
// SELF-CONTAINED: own port (9695), own SQLite file; the suite's shared
// stack is untouched.
// ═══════════════════════════════════════════════════════════════════

import { describe, it, expect, afterAll } from 'vitest'
import { spawn, type ChildProcess } from 'node:child_process'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { mkdirSync, rmSync } from 'node:fs'
import Database from 'better-sqlite3'
import { delay } from './helpers'
import {
  generateSuccessorPair,
  fetchJwksKids,
  pollJwksKids,
  buildRetirementNote,
} from '../scripts/op-key-rotate'
import { resolveOpSigningKey, signOpIdToken } from '../server/auth/op/keys'
import { validateIdToken, clearOidcCaches } from '@oimlsmart/platform-server/oidc'

const BROWSER_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const DB_DIR = join(BROWSER_DIR, '.cache', 'op-key-rotate')
const DB_PATH = join(DB_DIR, 'identity.db')

const ID_API = 9695
const BASE = `http://localhost:${ID_API}`

let api: ChildProcess | undefined
const logs: string[] = []

function killTreeHard(proc: ChildProcess | undefined): void {
  if (!proc || proc.exitCode !== null || proc.pid === undefined) return
  try { process.kill(-proc.pid, 'SIGKILL') } catch { /* group already gone */ }
  try { proc.kill('SIGKILL') } catch { /* already gone */ }
}

async function waitForHttp(url: string, timeoutMs: number): Promise<void> {
  const deadline = Date.now() + timeoutMs
  let lastError = ''
  while (Date.now() < deadline) {
    try {
      const res = await fetch(url)
      if (res.status < 500) return
      lastError = `HTTP ${res.status}`
    } catch (e) {
      lastError = String(e)
    }
    await delay(1_000)
  }
  throw new Error(`timed out waiting for ${url} (${lastError})\n--- stack logs ---\n${logs.join('').slice(-4000)}`)
}

/** Boot the identity API with the given OP_SIGNING_KEY against the
 *  SHARED DB file (the rotation's whole point: the key history lives in
 *  the database, the private key in the env). */
async function bootWithKey(privateJwkJson: string): Promise<void> {
  const inherited = Object.fromEntries(
    Object.entries(process.env).filter(([k]) => k !== 'NODE_ENV' && k !== 'VITEST' && !k.startsWith('VITEST_')),
  ) as NodeJS.ProcessEnv
  api = spawn(join(BROWSER_DIR, 'node_modules', '.bin', 'tsx'), ['server/serve.ts'], {
    cwd: BROWSER_DIR,
    env: {
      ...inherited,
      PORT: String(ID_API),
      DATABASE_PATH: DB_PATH,
      ENTITY_BACKEND: 'server',
      INSTANCE_PROFILE: join(BROWSER_DIR, 'e2e', 'fixtures', 'instance.profile.identity.yaml'),
      OIDC_ISSUER: '',
      OIDC_CLIENT_ID: '',
      OP_ISSUER: BASE,
      OP_SIGNING_KEY: privateJwkJson,
    },
    stdio: ['ignore', 'pipe', 'pipe'],
    detached: true,
  })
  api.stdout?.on('data', d => logs.push(String(d)))
  api.stderr?.on('data', d => logs.push(String(d)))
  await waitForHttp(`${BASE}/api/health`, 120_000)
}

async function stopApi(): Promise<void> {
  killTreeHard(api)
  api = undefined
  await delay(1_000)
}

afterAll(async () => {
  await stopApi()
})

describe('TODO.identity-ops/02 — the key-rotation ceremony (local stack)', () => {
  it('the ceremony: generate → rotate → the JWKS overlap → the old token survives → the retirement', { timeout: 360_000 }, async () => {
    mkdirSync(DB_DIR, { recursive: true })
    for (const suffix of ['', '-wal', '-shm']) rmSync(DB_PATH + suffix, { force: true })

    // The incumbent pair (key A), generated by the ceremony itself.
    const keyA = await generateSuccessorPair()
    expect(keyA.privateJwkJson).toContain('"kid":"' + keyA.kid + '"')
    expect(JSON.parse(keyA.privateJwkJson)).toMatchObject({ kty: 'EC', crv: 'P-256' })

    // The OP's own loader accepts the generated material and derives the
    // SAME kid (the script never announces a kid the OP would not serve).
    const loadedA = await resolveOpSigningKey({ OP_SIGNING_KEY: keyA.privateJwkJson })
    expect(loadedA.kid).toBe(keyA.kid)

    // Boot 1: the OP signs with A. An in-flight ID token is minted now.
    await bootWithKey(keyA.privateJwkJson)
    expect(await fetchJwksKids(BASE)).toEqual([keyA.kid])
    const nowSec = Math.floor(Date.now() / 1000)
    const inFlightToken = await signOpIdToken(loadedA, {
      iss: BASE,
      sub: 'contract-rotation-subject',
      aud: 'contract-rotation-rp',
      exp: nowSec + 3600,
      iat: nowSec,
      nonce: 'rotation-nonce',
    })
    clearOidcCaches()
    const claimsBefore = await validateIdToken(inFlightToken, {
      issuer: BASE, clientId: 'contract-rotation-rp', nonce: 'rotation-nonce', jwksUri: `${BASE}/jwks.json`,
    })
    expect(claimsBefore.sub).toBe('contract-rotation-subject')

    // The rotation: the successor pair (key B), the secret swap is a
    // RESTART with the new OP_SIGNING_KEY against the SAME database
    // (the local stand-in for `wrangler secret put`; --apply drives the
    // real store).
    const keyB = await generateSuccessorPair()
    expect(keyB.kid).not.toBe(keyA.kid)
    await stopApi()
    await bootWithKey(keyB.privateJwkJson)

    // The overlap assert (the ceremony's step 4): BOTH kids advertised.
    const overlap = await pollJwksKids(BASE, { expectKids: [keyA.kid, keyB.kid], timeoutMs: 60_000, intervalMs: 500 })
    expect(overlap.missing).toEqual([])

    // The in-flight token still verifies through the RP's real validator.
    clearOidcCaches()
    const claimsAfter = await validateIdToken(inFlightToken, {
      issuer: BASE, clientId: 'contract-rotation-rp', nonce: 'rotation-nonce', jwksUri: `${BASE}/jwks.json`,
    })
    expect(claimsAfter.sub).toBe('contract-rotation-subject')

    // The retirement note names the admin act and the old kid.
    const note = buildRetirementNote({ env: 'identity', kid: keyA.kid, retireAfterHours: 24, url: 'https://id.oimlsmart.org' })
    expect(note).toContain(`WHERE kid='${keyA.kid}'`)
    expect(note).toContain('oiml-smart-platform-identity')

    // The retirement (the documented admin act against the local DB):
    // the old kid leaves the JWKS, the new kid stays, the old token dies.
    await stopApi()
    const db = new Database(DB_PATH)
    db.prepare("UPDATE oidc_keys SET status='retired', retired_at=datetime('now') WHERE kid=?").run(keyA.kid)
    db.close()
    await bootWithKey(keyB.privateJwkJson)
    const retired = await pollJwksKids(BASE, { expectKids: [keyB.kid], absentKids: [keyA.kid], timeoutMs: 60_000, intervalMs: 500 })
    expect(retired.advertised).toEqual([keyB.kid])
    clearOidcCaches()
    await expect(validateIdToken(inFlightToken, {
      issuer: BASE, clientId: 'contract-rotation-rp', nonce: 'rotation-nonce', jwksUri: `${BASE}/jwks.json`,
    })).rejects.toThrow(/signature|token/)
  })
})
